# Generated by Django 2.2.2 on 2019-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('repo_name', models.CharField(max_length=250)),
                ('repo_url', models.URLField()),
                ('repo_language', models.CharField(max_length=250)),
            ],
        ),
    ]
