# Generated by Django 2.2.2 on 2019-06-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_repoinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepoInfo',
        ),
    ]
