# Generated by Django 2.2.2 on 2019-06-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_repoinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
