# Generated by Django 2.2.2 on 2019-06-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
